spring.application.name=CinemaApp
server.port=${PORT:8080}

# ========================
# NEON POSTGRESQL
# ========================
spring.datasource.url=jdbc:postgresql://ep-broad-sky-amvusd2r.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SUrnaz6e4vwL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# ========================
# JPA/HIBERNATE
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ========================
# SESSAO JDBC
# ========================
server.servlet.session.timeout=1800
server.servlet.session.cookie.name=CINEMA_SESSION
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=${COOKIE_SECURE:false}
server.servlet.session.tracking-modes=COOKIE
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.session.jdbc.table-name=SPRING_SESSION

# ========================
# THYMELEAF
# ========================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# ========================
# UPLOAD DE ARQUIVOS
# ========================
app.upload.dir=src/main/resources/static/uploads/
spring.web.resources.static-locations=classpath:/static/, file:src/main/resources/static/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ========================
# EMAIL (Gmail)
# ========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER:sitesteste99@gmail.com}
spring.mail.password=${MAIL_PASSWORD:Teste12345}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ========================
# ERROS
# ========================
server.error.include-stacktrace=on_param
server.mvc.pathmatch.matching-strategy=ant_path_matcher
